FROM ubuntu:latest

LABEL maintainer="wi-fi-hi@163.com"

RUN apt-get update && apt-get install -y \
    iproute2 \
    net-tools \
    && rm -rf /var/lib/apt/lists/*

#RUN ip link add veth0 type veth peer name veth1
#RUN ip link set veth0 up
#RUN ip link add link veth0 name veth0.10 type vlan id 10
#RUN ip link set veth0.10 up

EXPOSE 22


CMD ["bash", "-c", "service ssh start && sleep infinity" ]
